Declare volumes so docker-compose can create them
Prevents the following error while first building the image.

ERROR: Named volume "etc_pihole-unbound:/etc/pihole:rw"
is used in service "pihole" but no declaration was found
in the volumes section.